Update publish-nuget.yml

diff --git a/.github/workflows/publish-nuget.yml b/.github/workflows/publish-nuget.yml
--- a/.github/workflows/publish-nuget.yml
+++ b/.github/workflows/publish-nuget.yml
@@ -17,24 +17,32 @@ jobs:
         run: |
           # Gets all modified .csproj files in the last push's commits.
           echo -e "\033[36mFetching modified .csproj files in all commits from the current push...\033[0m"
+
+          # Determine the number of commits in the current push
+          COMMITS_COUNT=${{ github.event.commits && github.event.commits | length }}
+          if [ "$COMMITS_COUNT" -eq 0 ]; then
+            echo "::error::Unable to fetch the amount of commits in the current push."
+            exit 1
+          fi
           
           # Fetch full history to ensure valid references
           git fetch --prune --unshallow || true
-          git fetch origin master --depth=2 || true
+          git fetch origin master --depth=$COMMITS_COUNT || true
           
-          # Get the list of commit SHAs in this push
+          # Get the commit range based on the previous push
           PREVIOUS_SHA=${{ github.event.before }}
           if [ -z "$PREVIOUS_SHA" ] || ! git rev-parse "$PREVIOUS_SHA" >/dev/null 2>&1; then
-            PREVIOUS_SHA=$(git rev-list -n 1 HEAD~1)
+            echo "::error::Unable to fetch the previous push for file comparison."
+            exit 1
           fi
+
+          # Output commits
           echo -e "\033[36mCommits in the push:\033[0m"
-          COMMITS=$(git rev-list $PREVIOUS_SHA..${{ github.sha }})
+          COMMITS=$(git rev-list ${{ github.event.before }}..${{ github.sha }})
           echo "$COMMITS"
-          COMMITS=$({{ github.event.commits }} --count)
-          echo "Test number of commits: $COMMITS"
           
           # Get all modified projects
-          MODIFIED_PROJECTS=$(git diff --name-only $PREVIOUS_SHA..${{ github.sha }} | grep '\.csproj$' | sort | uniq || true)
+          MODIFIED_PROJECTS=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep '\.csproj$' | sort | uniq || true)
           
           # Output and filter modified projects
           FILTERED_PROJECTS=""
